# Frist stage - prepare the build folder
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

RUN npm run build

# Second stage - move it to NGINX
FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install --only=production

COPY --from=build /app/dist ./dist

CMD ["npm", "run", "start:prod"]
