version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: danilokrasic
      POSTGRES_DB: cv_db
      POSTGRES_PASSWORD: pass123

  test-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
# Start containers in detached / background mode
# docker-compose up -d

# Stop containers
# docker-compose down
