# Frist stage - prepare the build folder
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

RUN npm run build

# Second stage - move it to NGINX
FROM nginx:1.24

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
