version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"

  backend:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: cv-database
